"""Deterministic seed for the two demo tenants (CR-15).

Run once after `make demo`:

    docker compose run --rm api python -m scripts.seed

Creates (idempotent on re-run):

  * tenant "tnt_lending_demo"  — profile=consumer-lending, phi_mode=false
  * tenant "tnt_health_demo"   — profile=healthcare,       phi_mode=true

Issues one API key per tenant and writes them to `.env.local.seeds`
(gitignored) so the Makefile's `fire-webhook` target can pick up the
tenant UUIDs + keys without the operator having to copy anything.

Idempotency: tenants are UPSERTed on `name`; existing rows are reused
without re-issuing keys. The seed file is overwritten with the current
state on every run.
"""
from __future__ import annotations

import asyncio
from pathlib import Path
from uuid import UUID

import asyncpg

from app.auth import generate_key
from app.config import get_settings

TENANTS = [
    {
        "name": "tnt_lending_demo",
        "profile": "consumer-lending",
        "phi_mode": False,
        "active_adapter": "salesforce",
    },
    {
        "name": "tnt_health_demo",
        "profile": "healthcare",
        "phi_mode": True,
        "active_adapter": "salesforce",
    },
]


async def _upsert_tenant(
    conn: asyncpg.Connection, spec: dict[str, object]
) -> tuple[UUID, bool]:
    """Return (tenant_id, was_new). Idempotent by `name`."""
    row = await conn.fetchrow(
        "SELECT id FROM tenants WHERE name = $1", spec["name"]
    )
    if row is not None:
        tenant_id: UUID = row["id"]
        return tenant_id, False
    created = await conn.fetchrow(
        "INSERT INTO tenants (name, profile, phi_mode, active_adapter) "
        "VALUES ($1, $2, $3, $4) RETURNING id",
        spec["name"],
        spec["profile"],
        spec["phi_mode"],
        spec["active_adapter"],
    )
    assert created is not None
    tid: UUID = created["id"]
    return tid, True


async def _tenant_has_key(conn: asyncpg.Connection, tenant_id: UUID) -> bool:
    """True iff the tenant already has at least one api_keys row."""
    count = await conn.fetchval(
        "SELECT count(*) FROM api_keys WHERE tenant_id = $1", tenant_id
    )
    return int(count or 0) > 0


async def _issue_key_for_tenant(
    conn: asyncpg.Connection, tenant_id: UUID, prefix: str
) -> str:
    """Mint and persist a new API key for `tenant_id`. Returns the raw key."""
    raw, key_hash = generate_key(prefix=prefix)
    await conn.execute(
        "SELECT set_config('app.tenant_id', $1, true)", str(tenant_id)
    )
    await conn.execute("SELECT set_config('app.bootstrap', 'true', true)")
    await conn.execute(
        "INSERT INTO api_keys (tenant_id, key_hash, key_prefix) VALUES ($1, $2, $3)",
        tenant_id,
        key_hash,
        prefix,
    )
    return raw


async def _run() -> None:
    settings = get_settings()
    # Use the admin DSN so the seed can INSERT into tenants (no RLS) and
    # then SET LOCAL before the api_keys insert.
    conn = await asyncpg.connect(dsn=settings.admin_database_url)
    try:
        seeded: list[dict[str, str]] = []
        for spec in TENANTS:
            async with conn.transaction():
                tenant_id, _was_new = await _upsert_tenant(conn, spec)
                if await _tenant_has_key(conn, tenant_id):
                    seeded.append(
                        {
                            "name": str(spec["name"]),
                            "tenant_id": str(tenant_id),
                            "key": "(existing — see prior .env.local.seeds)",
                        }
                    )
                    continue
                raw = await _issue_key_for_tenant(
                    conn, tenant_id, settings.tenant_api_key_prefix
                )
                seeded.append(
                    {
                        "name": str(spec["name"]),
                        "tenant_id": str(tenant_id),
                        "key": raw,
                    }
                )

        # Write the seeds file at the repo root (inside the api container
        # that's /app). `.env.local.seeds` is gitignored.
        dest = Path("/app/.env.local.seeds")
        if not dest.parent.exists():
            dest = Path(".env.local.seeds")
        lines: list[str] = ["# Generated by scripts/seed.py — do not commit"]
        for row in seeded:
            safe = row["name"].upper()
            lines.append(f"TENANT_{safe}_ID={row['tenant_id']}")
            lines.append(f"TENANT_{safe}_KEY={row['key']}")
            # Short aliases used by the Makefile targets.
            if safe == "TNT_LENDING_DEMO":
                lines.append(f"TENANT_LENDING_ID={row['tenant_id']}")
                lines.append(f"TENANT_LENDING_KEY={row['key']}")
            elif safe == "TNT_HEALTH_DEMO":
                lines.append(f"TENANT_HEALTH_ID={row['tenant_id']}")
                lines.append(f"TENANT_HEALTH_KEY={row['key']}")
        dest.write_text("\n".join(lines) + "\n")

        # Echo to stdout so the caller can see what landed.
        print(f"Wrote {dest}:")
        for row in seeded:
            print(f"  {row['name']} -> {row['tenant_id']}")
    finally:
        await conn.close()


def main() -> None:
    asyncio.run(_run())


if __name__ == "__main__":
    main()
